project:
  type: website
  render: 
    - "*.qmd"
    - "!toxpipe-model-comparison"

website:
  back-to-top-navigation: true
  title: "ToxPipe Evaluation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - reports/eval.qmd
      - tools.qmd
      - about.qmd


format:
  html:
    theme: cosmo
    css: ntpweb-shared.css
    toc: true

execute:
  freeze: auto
