project:
  type: website

website:
  sidebar:
    search: true
    contents:
      - text: "Getting Started"
        href: index.qmd
      - text: "ABT-questionnaire"
        href: abt-question-ocr.qmd
      - text: "Evaluation application"
        href: eval.qmd
