---
title: "ABT Question OCR and Dataset generation"
author: "Amlan Talukder"
date: today
date-format: "MMM D, YYYY"
---

## Introduction

Questions from American Board of Toxicology (ABT) certification exams (2000-20007) were extracted. For a few exams (2005-2007), the answers were provided in tabulated format within a non-pdf file (e.g. MS Excel and MS Word). For the rest, both the questions and answers were provided as scanned pdf format. These pdf files were processed using [Amazon Textract](https://aws.amazon.com/textract/) which has OCR capability and "Azure GPT-4o" model.

## Processing steps of the pdf files

The questions and the answers were processed using the following steps:

### Step 1:

- The pdf files were uploaded to Amazon S3, as Amazon Textract does not allow "multipage" processing for on-premise files
- The relevant pages with questions and answers were filtered and preprocessed using regular expressions
- GPT-4o were used to list the questions and answers (both in string and tabular format) using separate prompts
- Each pdf file was processed separately

  **Command**

  ```python
  python abt-question-ocr/src/extraction_questions.py
  ```

### Step 2:

- The pdf outputs were combined with the non-pdf data

  **Notebook**

  ```
  abt-question-ocr/notebooks/combine_pdfs.ipynb
  ```

# Output format

The output file contains the following columns:

- *Question Index*: Consists of exam year, exam section (or part) and question number. For example, "2000A Q1" denotes the question 1 of the part A of the examination year 2000.
- *Questions*: The question extracted as it was in the pdf
- *Options*: The options extracted as they were in the pdf
- *Question Source*: The source pdf file name that contains the question
- *Answers*: The answer choice(s) for the question
- *Answer Source*: The source pdf file name that contains the answer