description: 'Short Tox Evaluation'

providers: 
  - file://providers.yaml

prompts:
  - file://prompt.yaml

tests:
  - file://

defaultTest:
  options:
    provider:
      id: openai:chat:azure-gpt-4o
      config:
        apiHost: 'litellm.toxpipe.niehs.nih.gov'

sharing:
  apiBaseUrl: https://evals.toxpipe.niehs.nih.gov
  appBaseUrl: https://evals.toxpipe.niehs.nih.gov 