description: 'Short Tox Evaluation'

providers: 
  # OpenAI Models

  - id: openai:chat:azure-gpt-4o
    label: GPT-4o
    config:
      temperature: 0

  - id: openai:chat:azure-gpt-4
    label: GPT-4 
    config:
      temperature: 0

  # - id: openai:chat:azure-gpt-4-turbo-20240409
  #   label: GPT-4 Turbo (2024-04-09)
  #   config:
  #     temperature: 0

  # # Anthropic Claude Models

  # - id: openai:chat:claude-3-5-sonnet
  #   label: Claude 3.5 Sonnet
  #   config:
  #     temperature: 0

  # - id: openai:chat:claude-3-opus
  #   label: Claude 3 Opus
  #   config:
  #     temperature: 0

  # # AI21 Models

  # - id: openai:chat:ai21-jurassic-2-ultra
  #   label: Jurassic 2 Ultra
  #   config:
  #     temperature: 0

  # - id: openai:chat:ai21-jamba-instruct
  #   label: Jamba-Instruct
  #   config:
  #     temperature: 0

  # # Amazon Models

  # - id: openai:chat:amazon-titan-text-premier
  #   label: Titan Text Premier
  #   config:
  #     temperature: 0

  # # Cohere Models

  # - id: openai:chat:cohere-command-r-plus
  #   label: Command R+
  #   config:
  #     temperature: 0

  # # Google Models

  # - id: openai:chat:gemini-1.5-pro
  #   label: Gemini 1.5 Pro
  #   config:
  #     temperature: 0

  # # Mistral Models

  # - id: openai:chat:mistral-large-2
  #   label: Mistral Large 2
  #   config:
  #     temperature: 0

  # - id: openai:chat:mistral-large
  #   label: Mistral Large
  #   config:
  #     temperature: 0

  # # Meta Models

  # - id: openai:chat:llama3-1-405b
  #   label: Llama 3.1 405B
  #   config:
  #     temperature: 0

  # - id: openai:chat:llama3-1-70b
  #   label: Llama 3.1 70B
  #   config:
  #     temperature: 0

  # - id: openai:chat:llama3-70b
  #   label: Llama 3 70B
  #   config:
  #     temperature: 0

prompts:
  - file://prompt.yaml

scenarios:
  - config:
    - vars:
      user_prompt:
        - "What are the primary mechanisms of toxicity for this chemical or its synonyms? Please describe the molecular and cellular processes involved in its toxic effects."
        - "Evaluate the potential biological effects of this chemical or its synonyms on the following organ systems: integumentary, skeletal, muscular, nervous, and endocrine. Provide specific impacts where known."
        - "Assess the potential biological effects of this chemical or its synonyms on the cardiovascular, lymphatic, respiratory, digestive, and urinary systems. Describe any known or predicted impacts."
        - "Analyze the potential biological effects of this chemical or its synonyms on the reproductive and immune systems. Include any known or suspected impacts on fertility, fetal development, and immune function."
        - "Describe the absorption characteristics of this chemical or its synonyms. Include information on potential routes of exposure, rate of absorption, and extent of absorption for each route."
        - "Evaluate the distribution patterns of this chemical or its synonyms in the body. Include information on volume of distribution, tissue distribution, ability to cross the blood-brain barrier, and potential for placental transfer."
        - "Describe the metabolism of this chemical or its synonyms. Include information on phase I and II reactions, known or predicted metabolite profiles, and any specific enzymes involved in its biotransformation."
        - "Analyze the excretion of this chemical or its synonyms. Describe the primary routes of excretion and the rate at which the compound is eliminated from the body."
        - "Assess the bioaccumulation potential of this chemical or its synonyms. Discuss its potential for accumulation in tissues and its persistence in the body."
        - "Provide information on the half-life of this chemical or its synonyms. Include biological half-life, effective half-life, and environmental half-life where applicable."
    tests:
      - vars:
          chemname: "Benzene"
        assert:
          

defaultTest:
  options:
    provider:
      id: openai:chat:azure-gpt-4o
      config:
        apiHost: 'litellm.toxpipe.niehs.nih.gov'

outputPath:
  - tier-1-tests.csv
  - tier-1-tests.html
  - tier-1-tests.json

sharing:
  apiBaseUrl: https://evals.toxpipe.niehs.nih.gov
  appBaseUrl: https://evals.toxpipe.niehs.nih.gov 