# Learn more: https://promptfoo.dev/docs/configuration/guide
description: 'ECSA GARA Challenge'

providers: 
  - id: openai:chat:azure-gpt-4o
    config:
      temperature: 0
  - id: openai:chat:azure-gpt-4
    config:
      temperature: 0
  - id: openai:chat:azure-gpt-4-turbo-20240409
    config:
      temperature: 0
  - id: openai:chat:claude-3-5-sonnet
    config:
      temperature: 0
  - id: openai:chat:claude-3-opus
    config:
      temperature: 0
  - id: openai:chat:ai21-jurassic-2-ultra
    config:
      temperature: 0
  - id: openai:chat:amazon-titan-text-premier
    config:
      temperature: 0
  - id: openai:chat:cohere-command-r-plus
    config:
      temperature: 0
  - id: openai:chat:gemini-1.5-pro
    config:
      temperature: 0
  - id: openai:chat:mistral-large
    config:
      temperature: 0

prompts:
  - 'What is the toxicodynamic activity and potential systemic availability of {{chemname}} or its synonyms with CAS number {{casrn}}? Please classify both as either high, medium, or low for mammals. Follow a read-across approach if only limited scientific information is available. Please give me the sources you take your information from.'

tests:
  - pfas.csv

defaultTest:
  options:
    provider:
      id: openai:chat:azure-gpt-4-turbo-20240409
      config:
        apiHost: 'litellm.toxpipe.niehs.nih.gov'

sharing:
  apiBaseUrl: https://evals.toxpipe.niehs.nih.gov
  appBaseUrl: https://evals.toxpipe.niehs.nih.gov 

outputPath:
  - ecsa_gara_challenge.csv
  - ecsa_gara_challenge.html
  - ecsa_gara_challenge.json