defaultTest:
  options:
    provider:
      embedding:
        id: openai:embedding:text-embedding-ada-002
description: Tests on agentic framework with toxicity type prompts for human
prompts:
  - Answer the following question with a list of string. List the {{effect_type}}
    of {{chemname}} or its synonyms with CAS number {{casrn}} on human
providers:
  - config:
      max_iterations: 10
      model: azure-gpt-4o
      summarize: 'false'
      temp: 0
    id: file://scripts/providers.py
    label: Toxipe (Agentic) [GPT-4o]
  - config:
      max_iterations: 10
      model: claude-3-5-sonnet
      summarize: 'false'
      temp: 0
    id: file://scripts/providers.py
    label: Toxipe (Agentic) [Claude-3.5 Sonnet]
  - config:
      max_iterations: 10
      model: gemini-1.5-pro
      summarize: 'false'
      temp: 0
    id: file://scripts/providers.py
    label: Toxipe (Agentic) [Gemini 1.5 Pro]
  - config:
      max_iterations: 10
      model: mistral-large
      summarize: 'false'
      temp: 0
    id: file://scripts/providers.py
    label: Toxipe (Agentic) [Mistral Large]
tests:
  - assert:
      - expected_phrases:
          - Gastrointestinal bleeding
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 50-78-2
      chemname: Aspirin
      effect_type: Sub acute toxicity
  - assert:
      - expected_phrases:
          - Hypothermia
          - Acidosis
          - Hepatocellular/liver injury
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 103-90-2
      chemname: Paracetamol
      effect_type: Sub acute toxicity
  - assert:
      - expected_phrases:
          - Acidosis
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 657-24-9
      chemname: Metformin
      effect_type: Sub acute toxicity
  - assert:
      - expected_phrases:
          - Weight gain
          - Increased appetite
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 53-03-2
      chemname: Prednisone
      effect_type: Sub acute toxicity
  - assert:
      - expected_phrases:
          - Altered liver function
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 1746-01-6
      chemname: Dioxin
      effect_type: Sub acute toxicity
  - assert:
      - expected_phrases:
          - Fatty degeneration of the heart
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 15502-74-6
      chemname: Arsenite
      effect_type: Sub acute toxicity
  - assert:
      - expected_phrases:
          - Loss of peripheral vision
          - Lack of coordination of movements
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 16056-34-1
      chemname: Methylmercury
      effect_type: Sub acute toxicity
  - assert:
      - expected_phrases:
          - Dizziness
          - Fatigue
          - Drowsiness
          - Headache
          - Loss of consciousness
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 75-01-4
      chemname: Vinylchloride
      effect_type: Sub acute toxicity
  - assert:
      - expected_phrases:
          - Gastrointestinal bleeding
          - Anemia
          - Chronic kidney disease
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 50-78-2
      chemname: Aspirin
      effect_type: Chronic toxicity
  - assert:
      - expected_phrases:
          - Osteoporosis
          - Weight gain
          - Increased appetite
          - Diabetes
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 53-03-2
      chemname: Prednisone
      effect_type: Chronic toxicity
  - assert:
      - expected_phrases:
          - Breast cancer
          - Endometrial cancer
          - Testis cancer
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 1746-01-6
      chemname: Dioxin
      effect_type: Chronic toxicity
  - assert:
      - expected_phrases:
          - Anemia
          - Bone marrow suppression
          - Immune suppression
          - Acute nonlymphocytic leukemia
          - Non-Hodgkin's lymphoma
          - 'Multiple myeloma '
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 71-43-2
      chemname: Benzene
      effect_type: Chronic toxicity
  - assert:
      - expected_phrases:
          - Anemia
          - Leukopenia
          - Liver damage
          - Hyperpigmentation
          - Hyperkeratosis
          - Polyneuritis and motor paralysis
          - Lung cancer
          - Skin cancer (in situ squamous cell carcinoma)
          - Bladder cancer
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 15502-74-6
      chemname: Arsenite
      effect_type: Chronic toxicity
  - assert:
      - expected_phrases:
          - Angiosarcoma of the Liver
          - Liver injury
          - Raynaud's phenomenon (blanching, numbness, and discomfort of the fingers
            upon exposure to cold)
          - Degeneration of the bones
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 75-01-4
      chemname: Vinylchloride
      effect_type: Chronic toxicity
  - assert:
      - expected_phrases:
          - Gastroschisis
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 50-78-2
      chemname: Aspirin
      effect_type: Developmental toxicity
  - assert:
      - expected_phrases:
          - Mental retardation
          - Cerebellar ataxia
          - Physical growth disorder
          - Dysarthria
          - Limb deformities
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 16056-34-1
      chemname: Methylmercury
      effect_type: Developmental toxicity
  - assert:
      - expected_phrases:
          - Hypersensitivity/allergic reaction
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 50-78-2
      chemname: Aspirin
      effect_type: Immune/lymphatic system toxicity
  - assert:
      - expected_phrases:
          - Edema
          - Immune suppression
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 53-03-2
      chemname: Prednisone
      effect_type: Immune/lymphatic system toxicity
  - assert:
      - expected_phrases:
          - Immune suppression
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 1746-01-6
      chemname: Dioxin
      effect_type: Immune/lymphatic system toxicity
  - assert:
      - expected_phrases:
          - Endometriosis
          - Decreased sperm count
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 1746-01-6
      chemname: Dioxin
      effect_type: Reproductive system toxicity
  - assert:
      - expected_phrases:
          - Ototoxicity
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 50-78-2
      chemname: Aspirin
      effect_type: Nervous system/Neurological toxicity
  - assert:
      - expected_phrases:
          - Ototoxicity
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 103-90-2
      chemname: Paracetamol
      effect_type: Nervous system/Neurological toxicity
  - assert:
      - expected_phrases:
          - Visual disturbances
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 657-24-9
      chemname: Metformin
      effect_type: Nervous system/Neurological toxicity
  - assert:
      - expected_phrases:
          - Amblyopia
          - Dry eyes
          - Eye hemorrhage
          - Glaucoma
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 134523-00-5
      chemname: Atorvastatin
      effect_type: Nervous system/Neurological toxicity
  - assert:
      - expected_phrases:
          - Delerium
          - Cataracts
          - Insomnia
          - Aggression
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 53-03-2
      chemname: Prednisone
      effect_type: Nervous system/Neurological toxicity
  - assert:
      - expected_phrases:
          - Drowsiness
          - Dizziness
          - Headache
          - Vertigo
          - Tremor
          - Delirium
          - Loss of consciousness
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 71-43-2
      chemname: Benzene
      effect_type: Nervous system/Neurological toxicity
  - assert:
      - expected_phrases:
          - Low IQ
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 16056-34-1
      chemname: Methylmercury
      effect_type: Nervous system/Neurological toxicity
  - assert:
      - expected_phrases:
          - Gastrointestinal bleeding
          - Ulcers
          - Autoimmune pancreatitis
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 50-78-2
      chemname: Aspirin
      effect_type: Digestive system toxicity
  - assert:
      - expected_phrases:
          - Hepatocellular/Liver injury
          - Pancreatitis
          - Oral erythema multiforme
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 103-90-2
      chemname: Paracetamol
      effect_type: Digestive system toxicity
  - assert:
      - expected_phrases:
          - Nausea
          - Vomiting
          - Hepatocellular injury
          - Cholestasis
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 657-24-9
      chemname: Metformin
      effect_type: Digestive system toxicity
  - assert:
      - expected_phrases:
          - Constipation
          - Pancreatitis
          - Liver toxicity
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 134523-00-5
      chemname: Atorvastatin
      effect_type: Digestive system toxicity
  - assert:
      - expected_phrases:
          - Pancreatitis
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 53-03-2
      chemname: Prednisone
      effect_type: Digestive system toxicity
  - assert:
      - expected_phrases:
          - Acidosis
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 103-90-2
      chemname: Paracetamol
      effect_type: Urinary system toxicity
  - assert:
      - expected_phrases:
          - Fixed drug eruption
          - Steven-Johnson syndrome
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 103-90-2
      chemname: Paracetamol
      effect_type: Integumentary system toxicity
  - assert:
      - expected_phrases:
          - Alopecia
          - Erythema multiforme
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 134523-00-5
      chemname: Atorvastatin
      effect_type: Integumentary system toxicity
  - assert:
      - expected_phrases:
          - Alopecia
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 53-03-2
      chemname: Prednisone
      effect_type: Integumentary system toxicity
  - assert:
      - expected_phrases:
          - Chloracne
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 1746-01-6
      chemname: Dioxin
      effect_type: Integumentary system toxicity
  - assert:
      - expected_phrases:
          - Rhabdomyloysis
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 134523-00-5
      chemname: Atorvastatin
      effect_type: Musculoskeletal system toxicity
  - assert:
      - expected_phrases:
          - Osteoporosis
          - Sarcopenia/Muscle weakness
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 53-03-2
      chemname: Prednisone
      effect_type: Musculoskeletal system toxicity
  - assert:
      - expected_phrases:
          - Monomorphic ventricular tachycardia
          - Sinus bradycardia
          - Atrioventricular block
          - Intracerebral hemmorhage
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 50-78-2
      chemname: Aspirin
      effect_type: Cardiovascular system toxicity
  - assert:
      - expected_phrases:
          - Myocardial ischemia
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 103-90-2
      chemname: Paracetamol
      effect_type: Cardiovascular system toxicity
  - assert:
      - expected_phrases:
          - Hypertension
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 53-03-2
      chemname: Prednisone
      effect_type: Cardiovascular system toxicity
  - assert:
      - expected_phrases:
          - Ventricular fibrillation
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 71-43-2
      chemname: Benzene
      effect_type: Cardiovascular system toxicity
  - assert:
      - expected_phrases:
          - Hypothyroidism
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 50-78-2
      chemname: Aspirin
      effect_type: Endocrine system toxicity
  - assert:
      - expected_phrases:
          - Hypothyroidism
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 657-24-9
      chemname: Metformin
      effect_type: Endocrine system toxicity
  - assert:
      - expected_phrases:
          - Diabetes
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 134523-00-5
      chemname: Atorvastatin
      effect_type: Endocrine system toxicity
  - assert:
      - expected_phrases:
          - Hyperglycemia
          - Diabetes
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 53-03-2
      chemname: Prednisone
      effect_type: Endocrine system toxicity
  - assert:
      - expected_phrases:
          - Thyroid disruption
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 1746-01-6
      chemname: Dioxin
      effect_type: Endocrine system toxicity
  - assert:
      - expected_phrases:
          - Asthma
          - Bronchospasm
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 103-90-2
      chemname: Paracetamol
      effect_type: Respiratory system toxicity
  - assert:
      - expected_phrases:
          - Mucous membrane irritation
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 71-43-2
      chemname: Benzene
      effect_type: Respiratory system toxicity
  - assert:
      - expected_phrases:
          - Autoimmune thrombocytopenia
          - Autoimmune agranulocytosis
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 50-78-2
      chemname: Aspirin
      effect_type: Hematological system toxicity
  - assert:
      - expected_phrases:
          - Thrombocytopenia
          - Neutropenia
          - Hemolytic anemia
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 103-90-2
      chemname: Paracetamol
      effect_type: Hematological system toxicity
  - assert:
      - expected_phrases:
          - Hemolytic anemia
          - Macrocytic anemia
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 657-24-9
      chemname: Metformin
      effect_type: Hematological system toxicity
  - assert:
      - expected_phrases:
          - Delayed wound healing
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 53-03-2
      chemname: Prednisone
      effect_type: Hematological system toxicity
  - assert:
      - expected_phrases:
          - Thrombocytopenia
          - Leukopenia
          - Anemia
          - Pancytopenia
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 71-43-2
      chemname: Benzene
      effect_type: Hematological system toxicity
  - assert:
      - expected_phrases:
          - "Bioavailability: 80\u2013100%, Protein binding 80\u201390%"
          - 'Elimination half-life: 15-30 hour'
          - 'Excretion: Urine (80-100%), Sweat, Saliva, Feces'
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 50-78-2
      chemname: Aspirin
      effect_type: Toxicokinetic parameters
  - assert:
      - expected_phrases:
          - "Half-life: 7\u201311 years"
        type: python
        value: file://scripts/tests.py
    description: Test similarity
    vars:
      casrn: 1746-01-6
      chemname: Dioxin
      effect_type: Toxicokinetic parameters
