# --------------------------------------------------------------
# Example:
# --------------------------------------------------------------
# abt-qa-assertion-prompts_mixed:
#   Evals to compare:
#     - - Base
#       - base-model_abt-qa-assertion-prompts_mixed
#     - - RAG
#       - rag_abt-qa-assertion-prompts_mixed
#     - - Agentic
#       - agentic_abt-qa-assertion-prompts_mixed
#   Name: ABT Q/A
# basic-prompts_human:
#   Evals to compare:
#     - - Base
#       - base-model_basic-prompts_human
#     - - RAG
#       - rag_basic-prompts_human
#     - - Agentic
#       - agentic_basic-prompts_human
#   Name: Basic prompts (Human)
# --------------------------------------------------------------

abt-qa-assertion-prompts_mixed:
  Evals to compare:
    - - Base
      - base-model_abt-qa-assertion-prompts_mixed
    - - RAG
      - rag_abt-qa-assertion-prompts_mixed
    - - Agentic
      - agentic_abt-qa-assertion-prompts_mixed
  Name: ABT Q/A
basic-prompts_human:
  Evals to compare:
    - - Base
      - base-model_basic-prompts_human
    - - RAG
      - rag_basic-prompts_human
    - - Agentic
      - agentic_basic-prompts_human
  Name: Basic prompts (Human)
basic-prompts_rat:
  Evals to compare:
    - - Base
      - base-model_basic-prompts_rat
    - - RAG
      - rag_basic-prompts_rat
    - - Agentic
      - agentic_basic-prompts_rat
  Name: Basic prompts (Rat)
tox-type-assertion-prompts_human:
  Evals to compare:
    - - Base
      - base-model_tox-type-assertion-prompts_human
    - - RAG
      - rag_tox-type-assertion-prompts_human
    - - Agentic
      - agentic_tox-type-assertion-prompts_human
  Name: Tox type prompts (Human)
tox-type-assertion-prompts_rat:
  Evals to compare:
    - - Base
      - base-model_tox-type-assertion-prompts_rat
    - - RAG
      - rag_tox-type-assertion-prompts_rat
    - - Agentic
      - agentic_tox-type-assertion-prompts_rat
  Name: Tox type prompts (Rat)
