# --------------------------------------------------------------
# Example:
# --------------------------------------------------------------
# abt-qa-assertion-prompts_mixed:
#   Evals to compare:
#     - base-model_abt-qa-assertion-prompts_mixed
#     - rag_abt-qa-assertion-prompts_mixed
#     - agentic_abt-qa-assertion-prompts_mixed
#   Name: ABT Q/A
# basic-prompts_human:
#   Evals to compare:
#     - base-model_basic-prompts_human
#     - rag_basic-prompts_human
#     - agentic_basic-prompts_human
#   Name: Basic prompts (Human)
# --------------------------------------------------------------

abt-qa-assertion-prompts_mixed:
  Evals to compare:
    - base-model_abt-qa-assertion-prompts_mixed
    - rag_abt-qa-assertion-prompts_mixed
    - agentic_abt-qa-assertion-prompts_mixed
  Name: ABT Q/A
basic-prompts_human:
  Evals to compare:
    - base-model_basic-prompts_human
    - rag_basic-prompts_human
    - agentic_basic-prompts_human
  Name: Basic prompts (Human)
basic-prompts_rat:
  Evals to compare:
    - base-model_basic-prompts_rat
    - rag_basic-prompts_rat
    - agentic_basic-prompts_rat
  Name: Basic prompts (Rat)
tox-type-assertion-prompts_human:
  Evals to compare:
    - base-model_tox-type-assertion-prompts_human
    - rag_tox-type-assertion-prompts_human
    - agentic_tox-type-assertion-prompts_human
  Name: Tox type prompts (Human)
tox-type-assertion-prompts_rat:
  Evals to compare:
    - base-model_tox-type-assertion-prompts_rat
    - rag_tox-type-assertion-prompts_rat
    - agentic_tox-type-assertion-prompts_rat
  Name: Tox type prompts (Rat)
